# fly.toml app configuration file generated for parse-dev on 2023-05-17T08:07:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parse-dev"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true

[[services]]
  protocol = ""
  internal_port = 3306

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
